### PR TITLE
New badge

### LINKED ISSUE #66: Update logo badge on acknowledgement page.
The badge on https://docs.signac.io/en/latest/acknowledge.html still shows our old logo. This should be updated.

### PR DESCRIPTION
**Pull request by bdice**
I updated the badge on the page "How to cite signac":
signac io-dark

I'm having difficulty making the SVG image show up at exactly 25px height, which is the target height for badges. I've tried everything I can think of. I'm not sure what to do, but I think if it's embedded in a README, it may show up at the wrong size. I'd appreciate further insight/help on that. Adobe Illustrator file attached below. It should be 104x25 pixels.
[signac.io-dark.ai.zip](https://github.com/glotzerlab/signac-docs/files/4110330/signac.io-dark.ai.zip)

Resolves #66.

### CODE REVIEW

**Comment by csadorf** [comment]
I'm not sure about the height issue, but I think it looks good and I'd recommend to keep the filenames the same so that existing badges are automatically updated.

**Comment by bdice** [comment]
@csadorf I avoided using the same filenames to avoid changing the sizes of badges that people may have already embedded. I can change it to match if you're sure that's the right approach and/or reviewers agree.

I was able to fix the height problems after trying again on my desktop -- it ended up being an issue of my laptop lying to me about true pixel heights because uses a high-DPI display mode.

@tcmoore3 @Charlottez112 This is ready for review. You can see the results here: https://docs.signac.io/en/new-badge/acknowledge.html

**Comment by bdice** [comment]
Also I updated my previous art files. They're all in the repository now (no .ai file anymore). Adobe Illustrator was being hard to work with so I used Inkscape for the final artwork.

**Comment by tcmoore3** [comment]
@Charlottez112, "approve" this PR if you think it's good to go!

**Pull request merged**
