### PR TITLE
Remove reference to removed script command.

### PR DESCRIPTION
**Pull request by csadorf**

### CODE REVIEW

**Comment by csadorf** [comment]
There are actually more references to the `script` command at: https://docs.signac.io/en/latest/templates.html

**Comment by bdice** [comment]
I'm working on this and will push changes to this branch.

**Comment by bdice** [comment]
@csadorf You're right, there were a _lot_ of references to the `script` command. I think I got them all. I deleted a lot of content in the process, and attempted to fix the logical flow of sections where large blocks of outdated content were removed. This will need to be reviewed with an eye for the context of the changes in the page, and not just looking at the diff.

**Comment by mikemhenry** [comment]
@bdice thanks for the heads up, I'll review this carefully -- do we have it setup where I can view the PR on RTD?

**Comment by syjlee** [comment]
@bdice I just went over the rendered doc and checked the changes based on the files changed(also the context of changes). Script command looks removed all over the doc. Will it be now under changelog/deprecated then?

**Comment by bdice** [comment]
@syjlee The `script` feature was removed in 0.14, we have it in the changelog. We just forgot to remove the feature from the documentation. https://github.com/glotzerlab/signac-flow/blob/d4a3c9de7aea3a1021c1665a6636c66dd79bfb06/changelog.txt#L70

If you're alright with this, please approve the pull request. Thanks!

**Comment by syjlee** [comment]
@bdice Oh, it was already removed long ago. I was searching it from the changelog of project core, not of project flow. My bad. I'm approving it now.

**Review by syjlee — APPROVED** [review]
All looks good to me.

**Pull request merged**
